### ISSUE TITLE
Tealium breaks android system language settings 

### ISSUE THREAD

**Issue by blablubb209** [Tealium/tealium-kotlin#219]
I have found a very strange issue regarding tealium sdk and android system language settings.
The source seems to be the Tealium.create call.
We use the following versions of tealium modules.

tealium-core = "1.5.2"
tealium-installreferrer = "1.1.0"
tealium-lifecycle = "1.2.0"
tealium-remotecommand = "1.3.0"
tealium-tagmanagement = "1.2.0"

Tested with
kotlin 1.8.21
Android API 29,33

Problem:
Android supports a list of languages via system settings and uses the highest prioritized supported language.
Our app supports english and german. If one of those has the highest priority everything works fine.
When we set the language list, via system settings, to spanish, german, english, our app will be forced to english instead of german.
This issues disappears when we remove our dispatchers and pass and emptySet instead to TealiumConfig() before calling Tealium.create().

issue exists:
<img width="847" alt="Screenshot 2023-06-27 at 10 06 17" src="https://github.com/Tealium/tealium-android/assets/88187335/eb7e1ce8-8528-4d3e-aadf-ca5b60b3ea79">

issue is fixed:
<img width="828" alt="Screenshot 2023-06-27 at 10 20 25" src="https://github.com/Tealium/tealium-android/assets/88187335/19b086b6-a463-4b59-9b1a-e071b32bba41">

It's very strange that Tealium causes this issue, any help would be appreciated.

**Comment by jameskeith** [comment]
@blablubb209 Thanks for raising this with us - I've transferred the issue to the `tealium-kotlin` repository since it seems to relate to this SDK, not the legacy Java one located at `tealium-android`

I'm having a little trouble replicating the behaviour though - I've setup a brand new multilingual app, that supports two languages as you have by providing a default set of `values.xml` for English and a translated set for Spanish. I've also declared the supported languages in the `build.gradle` so that Android doesn't automatically fallback to the default language as it sometimes does when the top preferred language doesn't have translations.
```
android {
   defaultConfig {
      // ...
      resConfigs "es", "en"
   }
}
```

I've setup my Android language preferences to use the following preferences `German -> Spanish -> English` - and this works fine for me. Even though I don't have translations for German, it still falls back to the non-default Spanish language as you would expect.

I have tried to get as close to your Tealium configuration as possible without any additional information, but obviously there are several things I cannot guess from your screenshots (like account/profile names, the settings/tagmananagement URL overrides  etc). I have been able to test adding and removing the TagManagement and Remote Command Dispatchers without any issues.
One thing I don't have access to is the two Remote Commands that you are importing. Could we try narrowing down whether removing one or both of those has any impact on the language behaviour?
Or even whether this is specific to one or the other Dispatcher?  by adding/removing one at a time.

**Comment by blablubb209** [comment]
Thanks for the quick response!
I narrowed it down further.  The issues occurs when TagManagementDispatcher gets passed to the Config.
`
dispatchers = mutableSetOf(TagManagementDispatcher)
`
I can provide additional information for the specific settings via e-mail if needed.

**Comment by jameskeith** [comment]
@blablubb209 - that seems like the best way to go from my perspective too. I appreciate that many things aren't necessarily best to share on GH issues. So feel free to raise a support ticket via email - support@tealium.com - and we can circle back with a solution on this thread later if necessary/appropriate.

**Comment by blablubb209** [comment]
The support was able to track down the issue.

- TagManagement Dispatcher uses a WebView to do all Tealium IQ features.
- This causes a known issue on Android 7.1+ as documented here - basically, instantiating any WebView causes the default Locale to be reset.  [https://issuetracker.google.com/issues/37113860](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fissuetracker.google.com%2Fissues%2F37113860&data=05%7C01%7Cchristian.c.wollbaum%40deutschebahn.com%7C77f5a9f9fd49425835f608db7712500c%7Ca1a72d9c49e64f6d9af65aafa1183bfd%7C0%7C0%7C638234692778681691%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zUccOSmabuA1m%2Fax082HGE0uheU70jleLmSWsm3meY8%3D&reserved=0)

Thanks a lot everyone!
