### ISSUE TITLE
Inspect traffic using Charles Proxy

### ISSUE THREAD

**Issue by JanIceTea** [Tealium/tealium-kotlin#48]
We use Charles proxy a lot to verify which events being sent to Tealium / Analytics. In iOS this works fine, however in Android it doesn't. Is there something we can set to enable it for debug builds?

**Comment by craigrouse** [comment]
@JanIceTea This is due to the default network security configuration on Android N (7.0)+. You can work around it for debugging purposes by adding some extra config to your app's manifest file. We have some instructions that explain this here:

https://community.tealiumiq.com/t5/Tealium-for-Android/Setting-up-Charles-to-Proxy-your-Android-Device/ta-p/5121#toc-hId-735733144

Please be aware you should change this back before shipping your app, as leaving this enabled leaves your app vulnerable to SSL attacks.

**Comment by JanIceTea** [comment]
Great, thanks. We will look into it.
